<?php
/**
 * vanet_car model config
 *
 * @author lidongxu
 */

$end_models['vanet_car'] = array(
	'type' => 'list', //表示这是一个列表型的模型，对应一个数据库的表
	'name' => '车辆信息',	//某型的名字，可以把一个栏目配置成某个模型
	'list_items'=>20, //后台每页显示
	'no_category'=>true,
	'category_fields'=> array(
		'name'=>array(
			'name'=>lang('name'),
			'type'=>'text',
			'null'=>true
		)
	),
	'fields' => array(
		'vin'=>array(
			'name'=>'车架号',
			'type'=>'text',
			'null'=>false
		),
		'init_mile'=>array(
			'name'=>'初始里程',
			'type'=>'text',
			'null'=>false
		),
		'engine_size'=>array(
			'name'=>'排量',
			'type'=>'text',
			'null'=>false
		),
		'license'=>array(
			'name'=>'车牌号',
			'type'=>'text',
			'null'=>false
		),
		'brand'=>array(
			'name'=>'品牌',
			'type'=>'text',
			'null'=>true
		),
		'model'=>array(
			'name'=>'型号',
			'type'=>'text',
			'null'=>true
		),
		'emissions'=>array(
			'name'=>'排量',
			'type'=>'text',
			'null'=>true
		),
		'maintenancemiles'=>array(
			'name'=>'保养里程数',
			'type'=>'text',
			'null'=>true
		),
		'initializemiles'=>array(
			'name'=>'初始里程',
			'type'=>'text',
			'null'=>true
		),
		'currentmiles'=>array(
			'name'=>'当前里程',
			'type'=>'text',
			'null'=>true
		),
		'roadfeesvalidity'=>array(
			'name'=>'养路费有效期',
			'type'=>'datetime',
			'null'=>true,
			'filter'=>'show_vanet_car_date'
		),
		'drivinglicensevalidity'=>array(
			'name'=>'行驶证有效期',
			'type'=>'datetime',
			'null'=>true,
			'filter'=>'show_vanet_car_date'
		),
		'insurancevalidity'=>array(
			'name'=>'保险有效期',
			'type'=>'datetime',
			'null'=>true,
			'filter'=>'show_vanet_car_date'
		),
		'comment'=>array(
			'name'=>'备注',
			'type'=>'text',
			'null'=>true
		),
		'status'=>array(
			'name'=>'状态',
			'type'=>'text',
			'null'=>true
		),
		'create_time'=>array(
			'name'=>'创建时间',
			'type'=>'datetime',
			'null'=>true,
			'filter'=>'show_vanet_car_date'
		),
		'nobd_id'=>array(
			'name'=>'nodb id',
			'type'=>'text',
			'null'=>true
		),
		'vehicle_name'=>array(
			'name'=>'车昵称',
			'width'=>'auto',
			'type'=>'text'
		),
		'vehicle_brand'=>array(
			'name'=>'车品牌',
			'width'=>'auto',
			'type'=>'text'
		),
		'vehicle_type'=>array(
			'name'=>'车型',
			'width'=>'auto',
			'type'=>'text'
		),
		'years'=>array(
			'name'=>'车龄',
			'width'=>'auto',
			'type'=>'text'
		)
	),
	'list_fields' => array(
		'car_id'=>array(
			'name'=>'ID',
			'width'=>'30',
			'sort'=>true,
			'align'=>'center',
		),
		'vin'=>array(
			'name'=>'车架号',
			'type'=>'text',
			'null'=>false
		),		
		'init_mile'=>array(
			'name'=>'初始里程',
			'type'=>'text',
			'null'=>false
		),
		'engine_size'=>array(
			'name'=>'排量',
			'type'=>'text',
			'null'=>false
		),	
		'license'=>array(
			'name'=>'车牌号',
			'width'=>'auto',
			'sort'=>true,
			'type'=>'text',
			'search'=>true
		),
		'brand'=>array(
			'name'=>'品牌',
			'width'=>'auto',
			'type'=>'text'
		),
		'model'=>array(
			'name'=>'型号',
			'width'=>'auto',
			'type'=>'text'
		),
		'comment'=>array(
			'name'=>'备注',
			'width'=>'auto',
			'type'=>'text'
		),
		'status'=>array(
			'name'=>'状态',
			'width'=>'auto',
			'type'=>'text',
			'search'=>true
		),
		'create_time'=>array(
			'name'=>'注册时间',
			'width'=>110,
			'sort'=>true,
			'filter'=>'show_vanet_car_date'
		),
		'vehicle_name'=>array(
			'name'=>'车昵称',
			'width'=>'auto',
			'type'=>'text'
		),
		'years'=>array(
			'name'=>'车龄',
			'width'=>'auto',
			'type'=>'text'
		),
		'_options'=>array(
			'name'=>'操作',
			'width'=>100,
			'filter'=>'show_vanet_car_options'
		)
	)
);

function show_vanet_car_date($t)
{
	return date('Y-m-d H:i',$t);
}

$end_rights[] = array(
	'name'=>'vanet_car',
	'description'=>'车辆数据',
	'rights'=>array('view','delete','update','add')
);

function show_vanet_car_options($car)
{
	end_show_view_button($car['car_id']);
	end_show_edit_button($car['car_id']);
	end_show_delete_button($car['car_id']);
}
